apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: lumenconcept-quotation-svc
  name: lumenconcept-quotation-svc
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      run: lumenconcept-quotation-svc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: lumenconcept-quotation-svc
    spec:
      containers:
      - name: lumenconcept-quotation-svc
        image: docker.io/farruza/lumenconcept-quotation
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: lumenconcept-quotation-svc
  name: lumenconcept-quotation-svc
  namespace: default
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    run: lumenconcept-quotation-svc
  sessionAffinity: None
  type: LoadBalancer
